# render.yaml
services:
  - type: web
    name: yuzu-bbs # あなたのWebサービス名に完全に一致させる
    env: python
    pythonVersion: 3.10.12 # これが非常に重要です
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      # DATABASE_URLをRenderのデータベースサービスから自動的に取得
      - key: DATABASE_URL
        fromDatabase:
          name: bbs-server # あなたのPostgreSQLデータベース名に完全に一致させる
          property: connectionString
