# render.yaml
services:
  - type: web
    name: yuzu-bbs # あなたのWebサービス名に完全に一致させる
    env: python
    pythonVersion: 3.10.12 # これが非常に重要です
    buildCommand: "pip install -r requirements.txt"
    # ここを修正します:
    startCommand: "python -c 'from app import db, app; with app.app_context(): db.create_all()' && gunicorn app:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bbs-server # あなたのPostgreSQLデータベース名に完全に一致させる
          property: connectionString
