# render.yaml
# このファイルは、プロジェクトのルートディレクトリに配置してください。

- type: web
  name: yuzu-bbs
  env: python
  pythonVersion: 3.10.12 # Renderがサポートする安定版のPythonバージョンを指定
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app
  autoDeploy: true
  envVars:
    - key: DATABASE_URL
      value: postgresql://bbs_user:YyVFVYn5u908BzpmaqkFQdmFkgBDVO44@dpg-d1kvc56r433s73d3490g-a/bulletin_board_data
